"""first migration

Revision ID: 75b0a5aa58af
Revises: 
Create Date: 2021-09-04 12:12:42.190795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b0a5aa58af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'groups', ['id'])
    op.create_unique_constraint(None, 'timetables', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'timetables', type_='unique')
    op.drop_constraint(None, 'groups', type_='unique')
    # ### end Alembic commands ###
