"""add fuckult column to timetable

Revision ID: da753750bd8e
Revises: 75b0a5aa58af
Create Date: 2021-09-08 20:30:20.893257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da753750bd8e'
down_revision = '75b0a5aa58af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('fuckult', sa.Enum('zf', 'df', 'mag_df', 'mag_zf', name='fuckultschedule', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetables', 'fuckult')
    # ### end Alembic commands ###
